Mvc/Areas/Tests/Controllers/BuiltInTagHelpersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Mvc.Areas.Tests.Model.BuiltInTagHelpers;

namespace Mvc.Areas.Tests.Controllers
{
    [Area("Tests")]
    public class BuiltInTagHelpersController : Controller
    {
        public IActionResult Index()
        {
            return View(
                new BuiltInTagHelpersIndexViewModel()
                {
                    Header = "Built-In Tag Helper Examples",
                    TagHelperLinks = new ActionLink[]
                    {
                        new ActionLink()
                        {
                            Url = Url.Action(nameof(Index)),
                            Content = nameof(Index)
                        },
                        new ActionLink()
                        {
                            Url = Url.Action(nameof(LoginForm)),
                            Content = nameof(LoginForm)
                        },
                        new ActionLink()
                        {
                            Url = Url.Action(nameof(Input)),
                            Content = nameof(Input)
                        },
                        new ActionLink()
                        {
                            Url = Url.Action(nameof(Select)),
                            Content = nameof(Select)
                        }
                    }
                }
                );
        }
        
        [HttpGet]
        public IActionResult LoginForm(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult LoginForm(LogInViewModel logInViewModel, string returnUrl = null)
        {
            if (!ModelState.IsValid)
            {
                ViewData["ReturnUrl"] = returnUrl;
                
                return View(logInViewModel);
            }
            
            if (!string.IsNullOrEmpty(returnUrl))
                return Redirect(returnUrl);

            return RedirectToAction(nameof(LoginForm));
        }

        [HttpGet]
        public IActionResult Input()
        {
            return View(
                new InputTodoItemsViewModel()
                {
                    TodoItems = new TodoItemViewModel[]
                    {
                        new TodoItemViewModel()
                        {
                            Name = "To finish the ASP.NET Core study",
                            IsDone = false
                        },
                        new TodoItemViewModel()
                        {
                            Name = "To end the electronic document flow",
                            IsDone = false
                        },
                        new TodoItemViewModel()
                        {
                            Name = "To accumulate the phone's battery",
                            IsDone = true
                        }
                    }
                }
            );
        }

        [HttpPost]
        public IActionResult Input(InputTodoItemsViewModel inputTodoItemsViewModel)
        {
            if (!ModelState.IsValid)
                return View(inputTodoItemsViewModel);

            return View("SavedInput", inputTodoItemsViewModel);
        }

        [HttpGet]
        public IActionResult Select()
        {
            return View(
                new SelectTechStackViewModel()
                {
                    Title = "Choose a Technology Stack",
                    CurrentTechStack = "nodejs",
                    TechStackItems = new SelectListItem[]
                    {
                        new SelectListItem("C#/ASP.NET Core", "aspnetcsharp"),
                        new SelectListItem("PHP/Apache", "phpapache"),
                        new SelectListItem("Ruby On Rails", "ruby"),
                        new SelectListItem("JavaScript/Node.Js", "nodejs"),
                        new SelectListItem("Java/Spring/Hibernate", "java"),
                    }
                }
            );
        }

        [HttpPost]
        public IActionResult Select(SelectTechStackViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            return Content($"Choosed a technology stack: {viewModel.CurrentTechStack}");
        }
        
    }
}

Mvc/Areas/Tests/Views/BuiltInTagHelpers/Index.cshtml
@using System.Net.Http
@model Mvc.Areas.Tests.Model.BuiltInTagHelpers.BuiltInTagHelpersIndexViewModel

@{
    ViewData["Title"] = "Built-In Tag Helpers - Index";
    
    
}

<h1>@Model.Header</h1>
<ul>
    @foreach (var tagHelperLink in Model.TagHelperLinks)
    {
        <li>
            @if (tagHelperLink.Url.ToLower().Contains("loginform"))
            {
                <a href="@(tagHelperLink.Url + "?returnUrl=" + Context.Request.Path)">@tagHelperLink.Content</a>
            }

            else
            {
                <a href="@tagHelperLink.Url">@tagHelperLink.Content</a>
            }
        </li>
    }
</ul>
Current Date Time: <cache>@DateTime.Now</cache>

Mvc/Areas/Tests/Views/BuiltInTagHelpers/Input.cshtml
@model Mvc.Areas.Tests.Model.BuiltInTagHelpers.InputTodoItemsViewModel

@{
    ViewData["Title"] = "Built-In Tag Helpers - Input";
}

@section StylesSection
{
    <style>
        .cell
            {
                border: 2px solid #bfbfbf;
                background-color: #fff9e6;
                padding: 20px;
                margin: 20px;
                text-align: center;
                display: inline-block;
            }
    </style>
}

<form asp-area="Tests"
      asp-controller="BuiltInTagHelpers"
      asp-action="Input"
      method="post"
      >
    @for (int i = 0; i < Model.TodoItems.Count; ++i)
    {
        <div class="cell">
            <p>
                <label asp-for="TodoItems[i].Name"></label>:<br>
                <textarea asp-for="TodoItems[i].Name"></textarea>
            </p>
            <p>
                <input asp-for="TodoItems[i].IsDone"/>&nbsp;
                <label asp-for="TodoItems[i].IsDone"></label> ?
            </p>
        </div>
        <br>
    }
    <button asp-area="Tests" asp-controller="BuiltInTagHelpers" asp-action="Input">Сохранить</button>
</form>

Mvc/Areas/Tests/Views/BuiltInTagHelpers/LoginForm.cshtml
@model Mvc.Areas.Tests.Model.BuiltInTagHelpers.LogInViewModel;

@{
    ViewData["title"] = "Built-In Tag Helpers - Form";
}

<form
    asp-area="Tests"
    asp-controller="BuiltInTagHelpers"
    asp-action="LoginForm"
    asp-route-returnUrl="@ViewData["ReturnUrl"]"
    >
    <div asp-validation-summary="All"></div>
    <p>
        <label asp-for="Login"></label>:&nbsp;
        <input asp-for="Login"/><br>
        <span asp-validation-for="Login"></span>
    </p>
    <p>
        <label asp-for="Password"></label>:&nbsp;
        <input asp-for="Password"/><br>
        <span asp-validation-for="Password"></span>
    </p>
    
    <p><button asp-area="Tests" asp-controller="BuiltInTagHelpers" asp-action="LoginForm">Войти</button></p>
</form>

Mvc/Areas/Tests/Views/BuiltInTagHelpers/SavedInput.cshtml
@model Mvc.Areas.Tests.Model.BuiltInTagHelpers.InputTodoItemsViewModel

@{
    ViewData["Title"] = "Built-In Tag Helpers - Saved Input";
}

@section StylesSection
{
    <style>
        table 
        {
            border-collapse: collapse;
        }
        
        th, td
        {
            border: 1px solid black;
        }
    </style>
}
<h1>Ваши задания:</h1>
<table>
    <thead>
    <tr>
        <th><label asp-for="TodoItems[0].Name"></label></th>
        <th><label asp-for="TodoItems[0].IsDone"></label></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var todoItem in Model.TodoItems)
    {
        <tr>
            <td>@todoItem.Name</td>
            <td>@(todoItem.IsDone ? "Да" : "Нет")</td>
        </tr>
    }
    </tbody>
    <tfoot>
        Кол-во заданий: @Model.TodoItems.Count
    </tfoot>
</table>

Mvc/Areas/Tests/Views/BuiltInTagHelpers/Select.cshtml
@model Mvc.Areas.Tests.Model.BuiltInTagHelpers.SelectTechStackViewModel

@{
    ViewData["Title"] = "Built-In Tag Helpers - Select";
}

<h1>@Model.Title</h1>
<form asp-area="Tests" asp-controller="BuiltInTagHelpers" asp-action="Select" method="post">
    <select asp-for="CurrentTechStack" asp-items="Model.TechStackItems"></select>    
    <br>
    <button asp-area="Tests" asp-controller="BuiltInTagHelpers" asp-action="Select">Save List</button>
</form>