Mvc/Areas/Files/Controllers/UploadsController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mvc.Areas.Files.Model.Uploads;
using System.Linq;
using System.Collections.Generic;

namespace Mvc.Areas.Files.Controllers
{
    [Area("Files")]
    public class UploadsController : Controller
    {
        [HttpGet]
        public IActionResult Single()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Single(FileUpload fileUpload)
        {
            if (!ModelState.IsValid)
                return View(fileUpload);

            try
            {
                await using (
                    var stream = 
                        System.IO.File.Create(
                            Path.Combine(
                                Path.GetTempPath(), fileUpload.FileToUpload.FileName
                                )
                            )
                        )
                {
                    await fileUpload.FileToUpload.CopyToAsync(stream);
                }
                
                return Ok(
                    $"File {fileUpload.FileToUpload.FileName} in size {fileUpload.FileToUpload.Length} uploaded !"
                );
            }
            
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        [HttpGet]
        public IActionResult Multiple()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Multiple(MultipleFilesUpload multipleFilesUpload)
        {
            if (!ModelState.IsValid)
                return View(multipleFilesUpload);

            var filesToUpload = multipleFilesUpload.FilesToUpload;
            
            MultipleFilesUploadResult result = new MultipleFilesUploadResult();
            
            foreach (var fileToUpload in filesToUpload)
            {
                try
                {
                    await using (
                        var stream =
                            System.IO.File.Create(
                                Path.Combine(
                                    Path.GetTempPath(), fileToUpload.FileName
                                )
                            )
                    )
                    {
                        await fileToUpload.CopyToAsync(stream);
                    }

                    result.UploadedFiles.Add(fileToUpload.FileName);
                }

                catch (Exception ex)
                {
                    result.NotUploadedFiles.Add(
                        new KeyValuePair<string, string>(
                                fileToUpload.FileName, ex.Message
                                )
                        );
                }
            }

            result.TotalFileUploadedSize =
                filesToUpload.Where(
                    f => result.UploadedFiles.Contains(f.FileName)
                ).Sum(f => f.Length);

            return View("MultipleResult", result);
        }
    }
}

Mvc/Areas/Files/Views/Uploads/Multiple.cshtml
@model MultipleFilesUpload

@{
    ViewData["Title"] = "Multiple files upload";
}

<h1>Multiple files upload:</h1>
<form
    enctype="multipart/form-data"
    method="post"
    asp-area="Files"
    asp-controller="Uploads"
    asp-action="Multiple">
    
    <label asp-for="FilesToUpload"></label>&nbsp;
    <input asp-for="FilesToUpload" type="file" multiple/><br>
    <span asp-validation-for="FilesToUpload"></span>
    <p>
        <input type="submit" asp-area="Files" asp-controller="Uploads" asp-action="Multiple" value="Send Files"/>
    </p>
</form>

Mvc/Areas/Files/Views/Uploads/MultipleResult.cshtml
@model MultipleFilesUploadResult

@{
    ViewData["Title"] = "Multiple files upload Result";
}

@section StylesSection
{
    <style>
       table {
       border-collapse: collapse;
       } 
       
       td {
       border:  1px solid green;
       }
    </style>
}

<h1>Result:</h1>
<h3>Total uploaded files size: @Model.TotalFileUploadedSize</h3>
<h3>Uploaded files: @string.Join(", ", Model.UploadedFiles)</h3>
@if (Model.NotUploadedFiles.Count > 0)
{
    <h3>Not uploaded files:</h3>
    <table>
        <thead>
        <tr>
            <th>File Name</th>
            <th>Error</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var errorFile in Model.NotUploadedFiles)
        {
            <tr>
                <td>@errorFile.Key</td>
                <td>@errorFile.Value</td>
            </tr>
        }
        </tbody>
    </table>
}

Mvc/Areas/Files/Views/Uploads/Single.cshtml
@model FileUpload

@{
    ViewData["Title"] = "Single fie upload";
}

<h1>Single file upload:</h1>
<form 
    enctype="multipart/form-data" 
    method="post" 
    asp-area="Files" 
    asp-controller="Uploads" 
    asp-action="Single"
    >
    <dl>
        <dt>
            <label asp-for="@Model.FileToUpload"></label>
        </dt>
        <dd>
            <input type="file" asp-for="@Model.FileToUpload"/><br>
            <span asp-validation-for="@Model.FileToUpload"></span>
        </dd>
    </dl>
    <input type="submit" asp-area="Files" asp-controller="Uploads" asp-action="Single" value="Send File"/>
</form>